// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Paybills.API.Infrastructure.Data;

#nullable disable

namespace Paybills.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260906023538_AddUserSettings")]
    partial class AddUserSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppUserBill", b =>
                {
                    b.Property<int>("BillsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("BillsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AppUserBill");
                });

            modelBuilder.Entity("AppUserReceiving", b =>
                {
                    b.Property<int>("ReceivingsId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("ReceivingsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("AppUserReceiving");
                });

            modelBuilder.Entity("Paybills.API.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmailToken")
                        .HasColumnType("text");

                    b.Property<bool>("EmailValidated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Paybills.API.Domain.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BillTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BillTypeId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Paybills.API.Domain.Entities.BillType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BillTypes");
                });

            modelBuilder.Entity("Paybills.API.Domain.Entities.Receiving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<bool>("Received")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReceivingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReceivingTypeId")
                        .HasColumnType("integer");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceivingTypeId");

                    b.ToTable("Receivings");
                });

            modelBuilder.Entity("Paybills.API.Domain.Entities.ReceivingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReceivingTypes");
                });

            modelBuilder.Entity("AppUserBill", b =>
                {
                    b.HasOne("Paybills.API.Domain.Entities.Bill", null)
                        .WithMany()
                        .HasForeignKey("BillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paybills.API.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppUserReceiving", b =>
                {
                    b.HasOne("Paybills.API.Domain.Entities.Receiving", null)
                        .WithMany()
                        .HasForeignKey("ReceivingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paybills.API.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Paybills.API.Domain.Entities.AppUser", b =>
                {
                    b.OwnsOne("Paybills.API.Domain.Entities.UserSettings", "Settings", b1 =>
                        {
                            b1.Property<int>("AppUserId")
                                .HasColumnType("integer");

                            b1.Property<bool>("CopyWithValues")
                                .HasColumnType("boolean");

                            b1.Property<int>("ItemsPerPage")
                                .HasColumnType("integer");

                            b1.HasKey("AppUserId");

                            b1.ToTable("Users");

                            b1.ToJson("Settings");

                            b1.WithOwner()
                                .HasForeignKey("AppUserId");
                        });

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Paybills.API.Domain.Entities.Bill", b =>
                {
                    b.HasOne("Paybills.API.Domain.Entities.BillType", "BillType")
                        .WithMany()
                        .HasForeignKey("BillTypeId");

                    b.Navigation("BillType");
                });

            modelBuilder.Entity("Paybills.API.Domain.Entities.Receiving", b =>
                {
                    b.HasOne("Paybills.API.Domain.Entities.ReceivingType", "ReceivingType")
                        .WithMany()
                        .HasForeignKey("ReceivingTypeId");

                    b.Navigation("ReceivingType");
                });
#pragma warning restore 612, 618
        }
    }
}
